### ISSUE TITLE
Use releases

### ISSUE THREAD

**Issue by tonyaldo1** [SirToffski/WireGuard-Ligase#1]
Great idea and project
I would like to suggest using github releases. This helps us "watch" releases and get notified by email when you release a new feature / bug fix

**Comment by SirToffski** [comment]
Thanks! I was considering doing so as well - but for whatever reason releases seemed more suited for binaries.

I'll do up an 1.0 when I get to fixing all opened issues ;)

**Comment by SirToffski** [comment]
Release 1.0 has been added with fixes for Quick-Setup script and QR code generation.
