### ISSUE TITLE
QR Code support

### ISSUE THREAD

**Issue by tonyaldo1** [SirToffski/WireGuard-Ligase#2]
After setting up a server/clients it would be nice to auto generate the config QR code for each client

qrencode -t ansiutf8 < client_1.conf

Just a suggestion for making a great project greater

**Comment by SirToffski** [comment]
Agreed, I was thinking they same thing while setting up a CentOS EC2 instance the other day. Will be added to release 1.0 :100:

**Comment by SirToffski** [comment]
Hi,

I've added the option to have QR codes generated.

Cheers,
Nick
