### ISSUE TITLE
number of clients

### ISSUE THREAD

**Issue by tonyaldo1** [SirToffski/WireGuard-Ligase#4]
Increasing the number of clients in quick_setup.sh and adding the respective number of client_private_address_<x> does not seem to be respected during the quick setup. I mean, quick setup will only create the 2 clients despite making the change above in advance of running the setup

**Comment by SirToffski** [comment]
Yeah this is a know bug I haven't gotten around fixing - it will work in Advanced setup / Client setup mode - for some reason I was having difficulties with a `for..i...do` loop when using variable `${client_number_["i"]}`. Now that I know someone is using it - a good time to review and fix it.

**Comment by SirToffski** [comment]
I've just pushed a commit that should make this work - I've tested it on Ubuntu 18.04 server and it worked for me. For example, if you specified 4 clients, the output would be something like shown below.

Let me know how this goes for you plz!

```
/// trimmed

4) 4 clients each with a public / private key; clients will have IPs of:

  10.100.100.10

  10.100.100.11

  10.100.100.12

  10.100.100.13

/// trimmed

  Generating server keys

  Generating server config

  Saving server config

Generating client 1 config

Adding client info to the server config

Generating client 2 config

Adding client info to the server config

Generating client 3 config

Adding client info to the server config

Generating client 4 config

Adding client info to the server config

/// trimmed

```
